# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Observability EmberJS Unit Test Job
on:
  schedule:
    - cron: "* */4 * * *"
  workflow_dispatch:

jobs:
  ubuntu-job:
    name: 'EmberJS Unit Tests on Test Observability'
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{secrets.BROWSERSTACK_USERNAME}}
          access-key: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
      - uses: actions/checkout@v3
        with:
          repository: emberjs/ember.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: node -v
      - run: npm install --force
      - run: npm install browserstack-node-sdk@latest
      - run: BROWSERSTACK_AUTOMATION=false npx browserstack-node-sdk mocha node-tests/blueprints/**/*-test.js
