# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Observability Sample p1 Job
on:
  schedule:
    - cron: "45 */2 * * *"
  workflow_dispatch:

jobs:
  test-multi-environment:
    name: 'WDIO Cucumber p1 Samples on Test Observability - ${{ matrix.environment }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [Europe, India]
        node-version: [18]
    environment: ${{ matrix.environment }}
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{secrets.BROWSERSTACK_USERNAME}}
          access-key: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: node -v
      - run: npm install
      - name: Run tests for ${{ matrix.environment }}
        env:
          TEST_ENVIRONMENT: ${{ matrix.environment }}
          BROWSERSTACK_HUB: ${{ vars.HUB_URL }}
        run: npm run e2e-test-wdio-cucumber-bs-p1
