# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Observability Sample Regression Job - Adarsh Mehta
on:
  schedule:
    - cron: "5 */4 * * *"
  workflow_dispatch:

jobs:
  ubuntu-job:
    name: 'WDIO Cucumber Samples on Test Observability'
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{secrets.BSTACK_UNAME_ADARSH}}
          access-key: ${{secrets.BSTACK_AKEY_ADARSH}}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: node -v
      - run: npm install
      - run: npm run e2e-test-wdio-cucumber-bs-regression
      - name: Save env variable
        if: always()
        run: echo "{BS_TESTOPS_BUILD_HASHED_ID}" >> "$GITHUB_ENV"
      - name: Print env variable
        if: always()
        run: echo "$GITHUB_ENV"
